language: java
install:
  - ls /usr/lib/jvm/
  - sudo add-apt-repository ppa:openjdk-r/ppa -y
  - sudo apt-get update -y
  - sudo apt-get install openjdk-8-jdk -y
script : mvn evosuite:generate evosuite:export test

